services:
  app:
    build: ./nextcloud
    depends_on:
      cache:
        condition: service_healthy
      database:
        condition: service_healthy
      imaginary:
        condition: service_healthy
    environment:
      - PHP_MEMORY_LIMIT=1024M
      - PHP_UPLOAD_LIMIT=1024G
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - NEXTCLOUD_TRUSTED_DOMAINS=webserver ffaabbii.de 192.168.178.112# Append your domain here
      - TRUSTED_PROXIES=172.30.0.0/12 192.168.178.0.0/16 192.178.178.112
      - POSTGRES_HOST=database
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
      - REDIS_HOST=cache     
    healthcheck:
      test: curl -sSf http://localhost/status.php | jq -e '(.installed==true) and (.maintenance==false) and (.needsDbUpgrade==false)'
      start_period: 30s
      interval: 15s
      timeout: 5s
    hostname: app
    image: app
    ports:
      - "55181:80"
    restart: unless-stopped
    volumes:
      - /nextcloud_data:/var/www/html/data
      - /nextcloud/app:/var/www/html
      - /nextcloud/config:/var/www/html/config
      - /nextcloud/custom_apps:/var/www/html/custom_apps
  cron:
    depends_on:
      app:
        condition: service_healthy
    entrypoint: ["/cron.sh"]
    image: app
    restart: unless-stopped
    stop_signal: SIGKILL
    volumes_from:
      - app

  notify_push:
    depends_on:
      app:
        condition: service_healthy
    entrypoint: ["/notify_push.sh"]
    environment:
      - NEXTCLOUD_URL=http://ffaabbii.de
    image: app
    ports:
      - "7867:7867"
    restart: unless-stopped
    stop_signal: SIGKILL
    user: www-data
    volumes_from:
      - app

  imaginary:
    build: ./imaginary
    environment:
      - MALLOC_ARENA_MAX=2
    healthcheck:
      test: curl -sSf http://localhost:9000/health
      start_period: 30s
      interval: 15s
      timeout: 5s
    restart: unless-stopped
 
  cache:
    build: ./redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_IO_THREADS=8
      - REDIS_IO_THREADS_DO_READS=yes
    healthcheck:
      test: redis-cli ping || exit 1
      start_period: 30s
      interval: 15s
      timeout: 5s
    restart: unless-stopped
    volumes:
      - /nextcloud/cache:/bitnami/redis
  database:
    build: ./postgresql
    user: "root"
    environment:
      - POSTGRESQL_DATABASE=nextcloud
      - POSTGRESQL_PASSWORD=nextcloud
      - POSTGRESQL_USERNAME=nextcloud
    healthcheck:
      test: pg_isready -U nextcloud || exit 1
      start_period: 30s
      interval: 15s
      timeout: 5s
    restart: unless-stopped
    volumes:
      - /nextcloud/database:/bitnami/postgresql
    tmpfs:
      - /docker-entrypoint-preinitdb.d
      - /docker-entrypoint-initdb.d
