services:
  app:
    build: ./nextcloud
    depends_on:
      cache:
        condition: service_healthy
      database:
        condition: service_healthy
      imaginary:
        condition: service_healthy
    environment:
<<<<<<< HEAD
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - NEXTCLOUD_TRUSTED_DOMAINS=webserver ffaabbii.de # Append your domain here
      - TRUSTED_PROXIES=172.30.0.0/12
    env_file:
      - ./cache.env
      - ./db.env
      - ./nextcloud.env
=======
      - PHP_MEMORY_LIMIT=1024M
      - PHP_UPLOAD_LIMIT=1024G
>>>>>>> upstream_caspar/main
    healthcheck:
      test: curl -sSf http://localhost/status.php | jq -e '(.installed==true) and (.maintenance==false) and (.needsDbUpgrade==false)'
      start_period: 30s
      interval: 15s
      timeout: 5s
    hostname: app
    image: app
    ports:
      - "55181:80"
    restart: unless-stopped
    volumes:
<<<<<<< HEAD
      - /etc/localtime:/etc/localtime
      - app:/var/www/html
      - config:/var/www/html/config
      - /cube_pool_mk_ii/tub/nextcloud_data:/var/www/html/data
=======
      - /pool-1/nextcloud/app:/var/www/html
      - /pool-1/nextcloud/config:/var/www/html/config
      - /pool-1/nextcloud/custom_apps:/var/www/html/custom_apps
      - /pool-0/nextcloud/data:/var/www/html/data
>>>>>>> upstream_caspar/main

  cron:
    depends_on:
      app:
        condition: service_healthy
    entrypoint: ["/cron.sh"]
    image: app
    restart: unless-stopped
    stop_signal: SIGKILL
    volumes_from:
      - app

  notify_push:
    depends_on:
      app:
        condition: service_healthy
    entrypoint: ["/notify_push.sh"]
    environment:
<<<<<<< HEAD
      - NEXTCLOUD_URL=http://webserver
      - PORT=52192
    image: nextcloud-app
    ports:
      - "52192:52192"
=======
      - NEXTCLOUD_URL=http://app
    image: app
    ports:
      - "7867:7867"
>>>>>>> upstream_caspar/main
    restart: unless-stopped
    stop_signal: SIGKILL
    user: www-data
    volumes_from:
      - app

<<<<<<< HEAD
  webserver:
    build: ./nginx
    depends_on:
      app:
        condition: service_started
    ports:
      - "55182:80"
    restart: unless-stopped
    volumes:
      - app:/var/www/html:ro
=======
  imaginary:
    build: ./imaginary
    environment:
      - MALLOC_ARENA_MAX=2
    healthcheck:
      test: curl -sSf http://localhost:9000/health
      start_period: 30s
      interval: 15s
      timeout: 5s
    restart: unless-stopped
>>>>>>> upstream_caspar/main

  cache:
    build: ./redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_IO_THREADS=8
      - REDIS_IO_THREADS_DO_READS=yes
    healthcheck:
      test: redis-cli ping || exit 1
      start_period: 30s
      interval: 15s
      timeout: 5s
    restart: unless-stopped
    volumes:
<<<<<<< HEAD
      - db:/var/lib/postgresql/data

volumes:
  app:
  config:
  data:
  db:
=======
      - /pool-1/nextcloud/cache:/bitnami/redis

  database:
    build: ./postgresql
    environment:
      - POSTGRESQL_DATABASE=nextcloud
      - POSTGRESQL_PASSWORD=nextcloud
      - POSTGRESQL_USERNAME=nextcloud
    healthcheck:
      test: pg_isready -U nextcloud || exit 1
      start_period: 30s
      interval: 15s
      timeout: 5s
    restart: unless-stopped
    volumes:
      - /pool-1/nextcloud/database:/bitnami/postgresql
    tmpfs:
      - /docker-entrypoint-preinitdb.d
      - /docker-entrypoint-initdb.d
>>>>>>> upstream_caspar/main
