version: '3'

services:
  app:
    build: ./nextcloud
    depends_on:
      cache:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - NEXTCLOUD_TRUSTED_DOMAINS=ffaabbii.de # Append your domain here
      - TRUSTED_PROXIES=172.16.0.0/12
    env_file:
      - ./cache.env
      - ./db.env
      - ./nextcloud.env
    healthcheck:
      test: sudo -u www-data sh -c "PHP_MEMORY_LIMIT=1G php /var/www/html/occ status --output=json | jq -e 'select(.installed==true and .maintenance==false)'" || exit 1
      start_period: 60s
    hostname: app
    image: nextcloud-app
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime
      - /var/lib/nextcloud/app:/var/www/html
      - /var/lib/nextcloud/config:/var/www/html/config
      - /cube_pool/nextcloud/data:/var/www/html/data

  cron:
    depends_on:
      app:
        condition: service_healthy
    entrypoint: ["/cron.sh"]
    env_file:
      - ./cache.env
      - ./db.env
      - ./nextcloud.env
    image: nextcloud-app
    restart: unless-stopped
    stop_signal: SIGKILL
    volumes_from:
      - app

  hpb:
    depends_on:
      app:
        condition: service_healthy
      webserver:
        condition: service_started
    entrypoint: ["/hpb.sh"]
    env_file:
      - ./cache.env
      - ./db.env
      - ./nextcloud.env
    environment:
      - NEXTCLOUD_URL=http://ffaabbii.de
      - PORT=52191
    image: nextcloud-app
    ports:
      - "52191:52191"
    restart: unless-stopped
    stop_signal: SIGKILL
    user: www-data
    volumes_from:
      - app

  webserver:
    build: ./nginx
    depends_on:
      app:
        condition: service_started
    ports:
      - "55181:80"
    restart: unless-stopped
    volumes:
      - /var/lib/nextcloud/app:/var/www/html:ro

  cache:
    build: ./redis
    env_file:
      - ./cache.env
    healthcheck:
      test: redis-cli ping || exit 1
      interval: 5s
    restart: unless-stopped
    volumes:
      - /var/lib/nextcloud/cache:/data

  db:
    build: ./postgres
    env_file:
      - ./db.env
    healthcheck:
      test: pg_isready -U nextcloud || exit 1
      interval: 5s
    restart: unless-stopped
    volumes:
      - /var/lib/nextcloud/db:/var/lib/postgresql/data
